version: "3.9"

services:
  influxdb:
    image: influxdb:2.7
    container_name: k6-influxdb
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${DOCKER_INFLUXDB_INIT_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${DOCKER_INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${DOCKER_INFLUXDB_INIT_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${DOCKER_INFLUXDB_INIT_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    volumes:
      - influx-data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:latest
    container_name: k6-grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana

  k6-runner:
    image: grafana/k6:latest
    container_name: k6-runner
    depends_on:
      - influxdb
    profiles: ["runner"]
    environment:
      K6_INFLUXDB_TOKEN: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      K6_ORG: ${DOCKER_INFLUXDB_INIT_ORG}
      K6_BUCKET: ${DOCKER_INFLUXDB_INIT_BUCKET}
      K6_SCRIPT: ${K6_SCRIPT}
      BASE_URL: ${BASE_URL}
      ENDPOINT_PATH: ${ENDPOINT_PATH}
      AUTH_MODE: ${AUTH_MODE}
    volumes:
      - ./scripts:/scripts:ro
      - ./results:/results
      - ./secrets:/scripts/secrets:ro
    command: >
      run
      --out influxdb=http://influxdb:8086/api/v2/write?org=${K6_ORG}&bucket=${K6_BUCKET}&precision=ns
      ${K6_SCRIPT}

volumes:
  influx-data:
  grafana-data:
