apiVersion: v1
kind: Pod
metadata:
  name: k6-rtp-smoke
  labels:
    app: k6-rtp-smoke
spec:
  restartPolicy: Never
  containers:
    - name: k6
      image: grafana/k6:latest
      # Equivalent of: k6 run /scripts/test_smoke.js
      command: ["k6"]
      args: ["run", "/scripts/test_smoke.js"]
      env:
        # === Inline your .env values here ===
        - name: BASE_URL
          value: "https://api.yourdomain.com"
        - name: ENDPOINT_PATH
          value: "/health"
        - name: AUTH_MODE
          value: "none"        # or "bearer"
        # If using bearer auth, you can either set TOKEN here or mount secrets/token.txt
        # - name: TOKEN
        #   value: "REPLACE_WITH_JWT"
        - name: RATE
          value: "2"           # requests per second
        - name: DURATION
          value: "30s"         # test duration
        - name: THRESHOLD_P90
          value: "2000"        # ms
        - name: ERROR_RATE_MAX
          value: "0.05"        # 5%
      volumeMounts:
        - name: scripts
          mountPath: /scripts
        - name: results
          mountPath: /results
        - name: secrets
          mountPath: /scripts/secrets
          readOnly: true
  volumes:
    # IMPORTANT: Replace __ABS_REPO_PATH__ with your absolute path to the repo folder on this host.
    - name: scripts
      hostPath:
        path: "__ABS_REPO_PATH__/scripts"
        type: Directory
    - name: results
      hostPath:
        path: "__ABS_REPO_PATH__/results"
        type: DirectoryOrCreate
    - name: secrets
      hostPath:
        path: "__ABS_REPO_PATH__/secrets"
        type: DirectoryOrCreate
